spring:
  datasource:
    url: jdbc:h2:mem:currency-conversion
    driverClassName: org.h2.Driver
    username: sa
    password:
  liquibase:
    change-log: classpath:liquibase/master.xml
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

application:
  conversion:
    currency:
      margin: 0.02
