---
openapi: 3.0.0
info:
  title: Conversion currency service
  description: With this service you will be able to calculate exchange rates
  contact:
    name: Sviridenko Artem
    email: vhavabox@gmail.com
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/hava36/currency-conversion-service/1.0.0
  description: SwaggerHub API Auto Mocking
- url: http://127.0.0.1
  description: conversion server
tags:
- name: users
  description: Available for all users
paths:
  /api/v1/currency/conversion:
    get:
      tags:
      - users
      summary: convert currency from one to another
      description: convert currency from one to another
      operationId: convertCurrency
      parameters:
      - name: currencyCodeFrom
        in: query
        description: source currency
        required: false
        style: form
        explode: true
        schema:
          maximum: 3
          minimum: 2
          type: integer
          example: 826
      - name: currencyCodeTo
        in: query
        description: destination currency
        required: false
        style: form
        explode: true
        schema:
          maximum: 3
          minimum: 2
          type: integer
          example: 978
      - name: currencyAmount
        in: query
        description: destination currency
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: number
          example: 123.21
      responses:
        "200":
          description: currency has been converted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrencyConversionResponse'
        "500":
          description: internal server error
        "503":
          description: server is unavailable
components:
  schemas:
    CurrencyConversionResponse:
      type: object
      properties:
        currencyFrom:
          $ref: '#/components/schemas/CurrencyResponse'
        currencyTo:
          $ref: '#/components/schemas/CurrencyResponse'
        margin:
          maximum: 1
          minimum: 0
          type: number
        currencyAmount:
          minimum: 0
          type: number
        totalAmount:
          minimum: 0
          type: number
    CurrencyResponse:
      type: object
      properties:
        code:
          maximum: 3
          minimum: 2
          type: integer
        description:
          maxLength: 40
          type: string
        alpha3:
          maxLength: 3
          type: string
        rates:
          type: array
          items:
            $ref: '#/components/schemas/RateResponse'
    RateResponse:
      type: object
      properties:
        id:
          minimum: 1
          type: integer
        currencyCode:
          maximum: 3
          minimum: 2
          type: integer
        rate:
          type: number
        multiplicity:
          type: number
